# Generated by Django 5.2 on 2025-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=34)),
                ('EJob', models.CharField(max_length=23)),
                ('ESal', models.FloatField(max_length=11)),
                ('Eaddr', models.CharField(max_length=23)),
            ],
        ),
    ]
